SELECT e.ITEM_ID, e.ITEM_NAME, e.RARITY
FROM ITEM_INFO e INNER JOIN ITEM_TREE d ON e.ITEM_ID = d.iTEM_ID 
WHERE d.PARENT_ITEM_ID IN (SELECT  T.PARENT_ITEM_ID  FROM ITEM_INFO E INNER JOIN ITEM_TREE T ON E.ITEM_ID = T.PARENT_ITEM_ID  WHERE RARITY = "RARE") 
ORDER BY ITEM_ID DESC